### ISSUE TITLE
SelectedTextBlock crash

### ISSUE THREAD

**Issue by zdpcdt** [irihitech/Semi.Avalonia#138]
![img_v2_0dace5ec-ca01-456d-9572-62c2dadf010g](https://user-images.githubusercontent.com/54255897/226799148-3d8a3253-b1a2-4aa0-8d30-08ebbef0e880.jpg)
Double-click here will cause the demo application crash.

**Comment by zdpcdt** [comment]
refer to https://github.com/AvaloniaUI/Avalonia/issues/10731

**Comment by rabbitism** [comment]
Closed by https://github.com/AvaloniaUI/Avalonia/pull/11231
