### ISSUE TITLE
Use Color where possible instead of SolidColorBrush in theme/resources

### ISSUE THREAD

**Issue by DevJohnC** [irihitech/Semi.Avalonia#143]
When writing my own control templates and themes that compliment Semi.Avalonia it's easier to do when I have access to Color primitives instead of SolidColorBrush instances.

A developer might want to write:

```
<SolidColorBrush x:Key="AcrylicColor" Color="{DynamicResource SemiBlue2}" />
```

But is currently unable to get at the actual color "SemiBlue2" without a converter because it's a brush instead of a color.

**Comment by rabbitism** [comment]
Hi @DevJohnC , this is implemented in version preview6.1. Feel free to provide your feedback.
