### ISSUE TITLE
Timepicker: set period item height to 40 to avoid app crush. 

### ISSUE THREAD

**Issue by rabbitism** [irihitech/Semi.Avalonia#153]
This is an Avalonia bug, but I need to hard code this item to avoid potential app crush when scrolling Period panel.

**Comment by rabbitism** [comment]
SURPRISINGLY only height 28 will cause crush. I will change all height to 30 atm. it will behaves exactly as FluentTheme.

**Comment by zdpcdt** [comment]
> SURPRISINGLY only height 28 will cause crush. I will change all height to 30 atm. it will behaves exactly as FluentTheme.

😦Amazing!
