### ISSUE TITLE
Buggy Text of TreeViewItem with 0.1.0-preview8

### ISSUE THREAD

**Issue by Developer-Alexander** [irihitech/Semi.Avalonia#187]
When using Semi.Avalonia version 0.1.0-preview8 with Avalonia version 11.0.0-preview8 the text of TreeViewItems is not shown correctly.

Instead of the actual text bound to that TreeViewItem the name of the class is displayed.

I will include a minimal project as example and for reproduction.

That's what the simeple app looks like without Semi.Avalonia enabled:
![grafik](https://github.com/irihitech/Semi.Avalonia/assets/74363317/a4150952-b2bd-4a33-9718-d5418cdef312)

That's what it looks like with Semi.Avalonia enabled:
![grafik](https://github.com/irihitech/Semi.Avalonia/assets/74363317/c1f02dc3-d64f-47d9-a854-f1f14b4f2a5e)

[SemiThemeTreeView.zip](https://github.com/irihitech/Semi.Avalonia/files/11572354/SemiThemeTreeView.zip)

**Comment by rabbitism** [comment]
Weird. I will take a look.

**Comment by Developer-Alexander** [comment]
Thx for the quick reaction.
Will there be 0.1.0-preview8.1 release including this fix?

**Comment by rabbitism** [comment]
> Thx for the quick reaction.
> Will there be 0.1.0-preview8.1 release including this fix?

afaik avalonia new preview/rc is coming this week. I will release with that.

**Comment by Developer-Alexander** [comment]
Great! Thanks alot!
