### ISSUE TITLE
Demo for Linux?

### ISSUE THREAD

**Issue by jinleil** [irihitech/Semi.Avalonia#189]
Is there a demo for Linux?  like this

![image](https://github.com/irihitech/Semi.Avalonia/assets/44106819/9bd3c77e-84cd-4ee6-9905-5405e8b4c94b)

**Comment by rabbitism** [comment]
Demo in this repo is crossplatform, you can just build and run it in your linux environment. I haven't try that yet but someone in wechat tried it and succeeded.
And Chinese is welcomed😁
