### ISSUE TITLE
Suggestion : Add classes and demo page for default typography

### ISSUE THREAD

**Issue by Al-Dyachkov** [irihitech/Semi.Avalonia#226]
It is very handy to provide consistent visual style
You can check out how it is done in Material.Avalonia 
[https://github.com/AvaloniaCommunity/Material.Avalonia](url)

![image](https://github.com/irihitech/Semi.Avalonia/assets/10960735/4948c736-8e3d-4f4b-8034-d4365ec90d21)

**Comment by rabbitism** [comment]
Hi, we are in the process of upgrating demos to be interactive by selecting different theme and classes. But they are not yet ready to be published. 

![image](https://github.com/irihitech/Semi.Avalonia/assets/14807942/ce578af0-c759-4d56-a0b0-af773e4a4f29)

**Comment by rabbitism** [comment]
But for now I think your suggestion is reasonable, we will add some hint first for textblocks.

**Comment by Al-Dyachkov** [comment]
Thank you, that will be very useful.
