### ISSUE TITLE
Suggestion : Add TreeDataGrid control theme

### ISSUE THREAD

**Issue by Al-Dyachkov** [irihitech/Semi.Avalonia#238]
It is a control provided and supported by Avalonia team, and they often suggest to use it over default datagrid port.
Lots of themes does not have support for it, so having theme for this control will help Avalonia.Semi to stand out

https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid

**Comment by rabbitism** [comment]
Will take a look.

**Comment by rabbitism** [comment]
https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/tree/master/src%2FAvalonia.Controls.TreeDataGrid%2FThemes

**Comment by rabbitism** [comment]
Surprisingly TreeDataGrid is targeting .net 5 instead of .net standard 2.0 ...
