### ISSUE TITLE
Стиль в DataGrid

### ISSUE THREAD

**Issue by KonstantinReim** [irihitech/Semi.Avalonia#243]
Подскажите пожалуйста, как поменять стиль заголовка, на стиль ячейки в DataGrid

**Comment by KonstantinReim** [comment]
Здравствуйте!
У меня есть вот такой код:
```
<DataGridTemplateColumn Width="52">
	<DataGridTemplateColumn.Header>
		<CheckBox Theme="{StaticResource CardCheckBox}"/>
	</DataGridTemplateColumn.Header>
	<DataGridTemplateColumn.CellTemplate>
		<DataTemplate>
			<CheckBox Theme="{StaticResource CardCheckBox}"/>
		</DataTemplate>
	</DataGridTemplateColumn.CellTemplate>
</DataGridTemplateColumn>
```
Я хочу применить стиль или тему CellTemplate для Header, чтобы в DataGrid выглядело все одинаково красиво.
Пробовал по разному, не получается, помогите пожалуйста!!!

**Comment by rabbitism** [comment]
Sorry was busy with all kinds of stuff. 
1. First of all, Avalonia built-in DataGrid only support universal ColumnHeader template, you can not assign different template to different columns. :(
2. Changing Header/HeaderTemplate will only impact the content inside header, but not the entire header. If you really want to change it, you should write another ControlTheme with the same` x:Key="{x:Type DataGridColumnHeader}"` so you can replace the default one in Semi.

**Comment by KonstantinReim** [comment]
Спасибо за ответ. Я Вас понял!!!
