### ISSUE TITLE
DataGrid Binding DynamicObject or System.Data.DataTable

### ISSUE THREAD

**Issue by YSW33** [irihitech/Semi.Avalonia#245]
我按照https://github.com/AvaloniaUI/Avalonia/issues/2781  绑定System.Data.DataTable，但是无效。

DataGrid 动态列Binding DataTable 该怎么做。
WPF里面直接可以绑定DynamicObject ，Avalonia绑定DynamicObject 无效。

**Comment by rabbitism** [comment]
Tutorials/DataGrid_With_ExpandoObject
