### ISSUE TITLE
Modal模态对话框有计划开发吗？

### ISSUE THREAD

**Issue by aaasoft** [irihitech/Semi.Avalonia#248]
感谢提供这么好的Avalonia主题，现在[Semi.Avalonia 11.0.0]用起来各方面都比较好。只是还缺少“Modal模态对话框”用来显示MessgeBox。请问这项功能有计划什么时候开发吗？

**Comment by rabbitism** [comment]
还在纠结中，不过肯定是放在Ursa项目中。

**Comment by aaasoft** [comment]
感谢，期待能早日用上。

**Comment by rabbitism** [comment]
FYI dialog已经在ursa中完成
