### ISSUE TITLE
Add Hex to color picker. 

### ISSUE THREAD

**Issue by rabbitism** [irihitech/Semi.Avalonia#256]
Color Picker should have the ability to show Hex value in dropdown button.

**Comment by rabbitism** [comment]
Reference: 
<img width="396" alt="image" src="https://github.com/irihitech/Semi.Avalonia/assets/14807942/51d15705-75a0-4187-ba15-69e8a8fdac13">

**Comment by zdpcdt** [comment]
Already Reapplied.
