### ISSUE TITLE
DataGrid disappears when IsEnabled is false

### ISSUE THREAD

**Issue by TeaDrivenDev** [irihitech/Semi.Avalonia#273]
Using Semi.Avalonia and Semi.Avalonia.DataGrid, a DataGrid disappears completely when its `IsEnabled` property is set to `false` (either directly in the markup or via binding). Only a grey rectangle is shown in its place.

Reproduced in the demo:

![2023-11-08 03_53_04-Semi Avalonia (Running) - Microsoft Visual Studio](https://github.com/irihitech/Semi.Avalonia/assets/2247219/9bc83253-774d-4953-9a3d-761e94a32fc2)

Surrounding the DataGrid with a container like a Grid, and setting the `IsEnabled` on that makes it work correctly; the DataGrid will be visible and in a disabled state.

**Comment by rabbitism** [comment]
We have fixed this issue. Please upgrade DataGrid package to version 11.0.1.1
