### ISSUE TITLE
how to set scrollbar style to be displayed directly internally and display it all the time

### ISSUE THREAD

**Issue by SmRiley** [irihitech/Semi.Avalonia#275]
if I want the default scrollbar style to be displayed directly internally, but also want to display it all the time, how should I set the style? It doesn't seem to work when I use this method
```xaml
<Style Selector="ScrollBar /template/ ScrollBar#PART_VerticalScrollBar">
      <Setter Property="Opacity"
              Value="1" />
  </Style>
```

_Originally posted by @SmRiley in https://github.com/irihitech/Semi.Avalonia/issues/175#issuecomment-1818165787_

**Comment by rabbitism** [comment]
Hello, 
First of all, the selector should be `ScrollViewer /template/  ScrollBar#PART_VerticalScrollBar`
Secondly, the 0 opacity is set directly in template as local value, which has a higher priority than style setter value, so your style setter will not take effect. 

I pushed in branch 275-scroll, move the default value to style setter. and your style setter will work. You can copy this new template to your project if you don't want to wait for next release (will not happen in near future)

**Comment by SmRiley** [comment]
> Hello, First of all, the selector should be `ScrollViewer /template/ ScrollBar#PART_VerticalScrollBar` Secondly, the 0 opacity is set directly in template as local value, which has a higher priority than style setter value, so your style setter will not take effect.
> 
> I pushed in branch 275-scroll, move the default value to style setter. and your style setter will work. You can copy this new change to your project as default control theme if you don't want to wait for next release (will not happen in near future)
> 
> [main...275-scroll](https://github.com/irihitech/Semi.Avalonia/compare/main...275-scroll)

ok,thx
