### ISSUE TITLE
How to inherit semi.avalonia ControlTheme by custom resource file

### ISSUE THREAD

**Issue by cliffliu123** [irihitech/Semi.Avalonia#300]
Hi @rabbitism 

Like following snapshot , I always cannot find semi.avalonia's control theme to inherit .
Could you give me some tips ? 
Note: my project app.axaml had include Semi.Avalonia.

Thanks.
![image](https://github.com/irihitech/Semi.Avalonia/assets/6345353/bcba694f-b248-4a25-9c15-77c99bf793d8)

**Comment by rabbitism** [comment]
datagrid related are in another assembly.

**Comment by cliffliu123** [comment]
Thanks for your reply , 
But the button control theme in resource , also cannot inherit.

Could give me some tips ?
Thanks.

![image](https://github.com/irihitech/Semi.Avalonia/assets/6345353/2cac3a00-7bc1-4016-9da7-54109c8b9f62)

**Comment by rabbitism** [comment]
This is what I do. 
![image](https://github.com/irihitech/Semi.Avalonia/assets/14807942/7827df86-2576-48f9-9245-955126b7a423)

Notice that there should be a warning because compiler at this point cannot guarantee the existence of this key.

**Comment by cliffliu123** [comment]
Thanks for your reply, it's successful.
