### ISSUE TITLE
Semi.Avalonia的demo中，进行发布的时候会报错，不能正常发布

### ISSUE THREAD

**Issue by xingwa** [irihitech/Semi.Avalonia#325]
Semi.Avalonia的demo中，进行发布的时候会报错（勾选了裁剪未使用的代码选项），不能正常发布。
如果不勾选裁剪未使用的代码选项 就能正常发布。

![微信图片_20240324180907](https://github.com/irihitech/Semi.Avalonia/assets/15813393/5ee0bb63-1f48-4ffd-90e7-1e51018072e7)
![Uploading 微信图片_20240324181016.png…]()

**Comment by rabbitism** [comment]
duplicate
