### ISSUE TITLE
DataGrid滚动条问题

### ISSUE THREAD

**Issue by enycw001** [irihitech/Semi.Avalonia#362]
水平和垂直进度条同时出现的时候会出现这个问题,水平进度条会有一半覆盖掉最后一行的内容
请看图
![QQ截图20240611035926](https://github.com/irihitech/Semi.Avalonia/assets/9591833/bf661526-2460-4663-ac2e-5c7cbbb7da52)

**Comment by rabbitism** [comment]
Sorry 忘记回复了，因为Semi的设计语言是滚动条覆盖内容的，所以我们也设计成了这样子，我们意识到有时候这样不好用，所以我们给ScrollViewer提供了一个不覆盖的选项，但是我们忘记了DataGrid不是用ScrollViewer的，我们后续会fix。
