### ISSUE TITLE
Bolded text is blurry in 11.1.0 compared to previous versions

### ISSUE THREAD

**Issue by Hertzole** [irihitech/Semi.Avalonia#395]
After updating to 11.1.0 all the text for both text blocks and buttons (I think everything that is bolded in some way) has become very blurry and hard to read. 

Is this intended? Might also be related to https://github.com/irihitech/Semi.Avalonia/issues/360 but I'm not sure.

This can also be seen in the demo application.
![image](https://github.com/user-attachments/assets/4dbb2fee-172e-4644-9c75-64c1b6dd9cf5)
![image](https://github.com/user-attachments/assets/3a99663b-25c3-421b-9bd1-ef32c83d2e85)

**Comment by rabbitism** [comment]
Unfortunately this is not something we can fix. Please check this comment

https://github.com/AvaloniaUI/Avalonia/issues/15015#issuecomment-2104254132

**Comment by Hertzole** [comment]
Ah, I didn't find that issue! Thank you!
Even after adding those `CompositionOptions`, everything is still blurry. Is this a side effect of me using the Semi theme?

**Comment by rabbitism** [comment]
> Ah, I didn't find that issue! Thank you! Even after adding those `CompositionOptions`, everything is still blurry. Is this a side effect of me using the Semi theme?

It should be a problem of Microsoft YaHei IMHO. But surprisingly it works well in 11.2.0-alpha (you can try after setup Avalonia nightly feed and switch to Semi deploy-trial branch)

**Comment by Hertzole** [comment]
That sounds promising! I'll eagerly be waiting for the next version then. :)
