### ISSUE TITLE
FontWeight of Button is Bold defaultly

### ISSUE THREAD

**Issue by NeverMorewd** [irihitech/Semi.Avalonia#438]
Semi.Avalonia 11.1.0.4 latest
Avalonia 11.1.3 latest
.net 8

nuget:
![image](https://github.com/user-attachments/assets/ef07ec73-a61b-4cd1-aef3-358fd3d0ccb4)

app.axaml
![image](https://github.com/user-attachments/assets/6ed7c02a-5ecf-4122-8599-b644e713ccb2)

MainWindow.axaml
![image](https://github.com/user-attachments/assets/208d28d0-44a1-4a57-8a6b-1599fea247c3)

screenshot
![cee0ad307ed718787c5268d3c5b4e83](https://github.com/user-attachments/assets/b9c9e828-9a1c-4d83-ba2f-ef766b0b6d23)

**Comment by rabbitism** [comment]
Yes this is by Semi design guideline. 
![image](https://github.com/user-attachments/assets/28b8b9eb-0a28-475a-b00f-05317300d57a)
There is display issue in Avalonia 11.1, it will be back to normal in 11.2 (confirmed in beta)
