### ISSUE TITLE
Button text not bold by default in Avalonia 11.2

### ISSUE THREAD

**Issue by genment** [irihitech/Semi.Avalonia#450]
[`ButtonDefaultFontWeight`](https://github.com/search?q=repo%3Airihitech%2FSemi.Avalonia%20ButtonDefaultFontWeight&type=code) seems not working.

![b6d175ffff2acd71034d4c1c0fdb93da](https://github.com/user-attachments/assets/54a2d389-4c3e-4447-a773-a599dd7c7a83)

**Comment by rabbitism** [comment]
Somehow, it works well in new created Avalonia 11.2 projects...

**Comment by zdpcdt** [comment]
An interesting phenomenon:
When I transferred the ButtonDemo into a newly created Avalonia 11.2 project, the result was the same as in the Semi.Avalonia.Demo.
![image](https://github.com/user-attachments/assets/c2e2ae06-f983-4e9f-b698-bd9ba4938909)

After deleting the TextBlock labeled `Light (Default)` and rerunning the project, the FontWeight of the Button was restored to Bold.
![image](https://github.com/user-attachments/assets/fb94487d-d3d8-459d-a3d6-d85c07d2e93d)

Similarly, directly modifying the ButtonDemo in Semi.Avalonia.Demo only shows changes in the Previewer, while the FontWeight issue persists when actually running the project.

**Comment by zdpcdt** [comment]
This issue is not limited to the `Button`; it affects any control that uses `FontWeight`. Examples include `TitleLabel`, `TitleTextBlock`, `ButtonRadioGroupListBox`, `NotificationCard`, etc.

**Comment by rabbitism** [comment]
Pretty sure this is a upstream issue and already fixed in 11.2.1
