### ISSUE TITLE
Semi Avalonia 11.2.1 NativeAOT failed on Win7

### ISSUE THREAD

**Issue by rabbitism** [irihitech/Semi.Avalonia#474]
![5f3be9ae13671f7a0a0fbfe1b3de45a3](https://github.com/user-attachments/assets/a4eebbf0-43de-46a3-a7f2-5a1af8ebdf98)

works well with Semi 11.1.0.4 + Avalonia 11.2.1
works well with Fluent 11.2.1 + Avalonia 11.2.1

.NET9.

**Comment by zdpcdt** [comment]
The issue appears to be caused by an incorrect abbreviation for Ukrainian.

![img_v3_02gr_4dfabe25-7981-4aa6-a2b2-eb486264ff2g](https://github.com/user-attachments/assets/0ea46f34-29c0-46c3-b903-4e5d4fd51c12)
