### ISSUE TITLE
Bug：窗口功能按钮显示不全

### ISSUE THREAD

**Issue by hewenbin11** [irihitech/Semi.Avalonia#477]
新建Semi项目，创建空窗口，设置宽高为500*400

**当以下状态时**
```cs
ExtendClientAreaToDecorationsHint="True"
```

**出现：**

窗口按钮在点击最大化后，按钮在鼠标悬浮时被裁切，从而导致显示不完全（见图一）；

当从默认窗口大小直接进入全屏时不会触发该问题（见图三）

该问题出现在点击最大化按钮后，此时点击全屏也会出现按钮显示不完全的问题（见图四）。

以下为WIndow设置：

```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="500" d:DesignHeight="400"
        x:Class="Photo_Border.Home_Page"
		RequestedThemeVariant="Light"
		ExtendClientAreaChromeHints="Default"
		Icon="/Assets/avalonia-logo.ico"
		ExtendClientAreaToDecorationsHint="True"
		WindowStartupLocation="CenterScreen"
		SystemDecorations="Full">

```

---

![点击最大化后](https://github.com/user-attachments/assets/7b8916ab-2ff5-4b76-9ca7-8ffe87faf956)

图一：点击最大化后按钮显示不全
---

![默认大小](https://github.com/user-attachments/assets/d70e1e16-501b-42bb-b14f-9f3abbd1118d)

图二：正常状态
---

![直接进入全屏](https://github.com/user-attachments/assets/34800bbe-98f4-4a66-a5aa-38c8eebdc917)

图三：从默认窗口大小直接进入全屏
---

![从最大化进入全屏](https://github.com/user-attachments/assets/8c75d890-e8eb-4bf9-8241-3b886b9b5abc)

图四：从最大化进入全屏
---

**Comment by rabbitism** [comment]
Pretty sure this is controlled by `ExtendClientAreaTitleBarHeightHint`. for Semi Avalonia if you extend client, you need to explicitly set to a value (iirc 36).
你需要给ExtendClientAreaTitleBarHeightHint设置一个适合的值。（我记得是36）

**Comment by rabbitism** [comment]
@zdpcdt can we have a predefined class for window, for easier borderless window setup?
