### ISSUE TITLE
[Bug] Website is too zoomed in

### ISSUE THREAD

**Issue by MeltyObserver** [irihitech/Semi.Avalonia#479]
the preview website is overly zoomed in i can't even browse it, this happens on firefox on linux and it doesn't even load on mobile...

![image](https://github.com/user-attachments/assets/2e1b1b96-e135-4c9e-83f0-fb54bc1a673a)

**Comment by zdpcdt** [comment]
Semi.Avalonia is not specifically optimized for mobile devices or web platforms. However, we recently added a button to collapse the TabControl, which might help improve the browsing experience.

**Comment by MeltyObserver** [comment]
Actually, I want to apologize... the issue turned out to be on my side, I'm using librewolf with `ResistFingerprinting` enabled and that messes with Avalonia when it tries to get the dimensions of my browser.

sorry...
