### ISSUE TITLE
如何设置全局的主题颜色？

### ISSUE THREAD

**Issue by howzew** [irihitech/Semi.Avalonia#505]
semi默认的主题颜色是蓝色，但我希望自己设置全局的主题颜色
我看到通过ThemeVariant提供了几种颜色
但我如何自己设置呢？
如果我希望自动保持为当前电脑的主题色呢？（avalonia官方的主题色就是和系统主题色一致的）

**Comment by rabbitism** [comment]
Semi Avalonia 无法提供便捷的全局主题色自由切换，也无法提供便捷的系统主题色同步。
Semi Design并未提供色阶算法，因此我们无法从一个主题色推导出相关颜色（例：无法从按钮背景色推导出悬停和按下的背景色）。Fluent主题内置的算法过于粗糙了，完全无法接受。
想要跟随电脑的主题色非常简单，在Avalonia中获取IPlatformSettings，就可以订阅ColorValuesChanged事件了。如果你有自己实现的色阶算法，那么就可以按照我们提供的Token把相应的动态资源都换掉。

**Comment by howzew** [comment]
> Semi Avalonia 无法提供便捷的全局主题色自由切换，也无法提供便捷的系统主题色同步。 Semi Design并未提供色阶算法，因此我们无法从一个主题色推导出相关颜色（例：无法从按钮背景色推导出悬停和按下的背景色）。Fluent主题内置的算法过于粗糙了，完全无法接受。 想要跟随电脑的主题色非常简单，在Avalonia中获取IPlatformSettings，就可以订阅ColorValuesChanged事件了。如果你有自己实现的色阶算法，那么就可以按照我们提供的Token把相应的动态资源都换掉。

感谢你的解答，那我那是用默认吧，用semi的原因就是因为便捷、好用、好看，如果整复杂了，就失去初衷了

**Comment by rabbitism** [comment]
> 感谢你的解答，那我那是用默认吧，用semi的原因就是因为便捷、好用、好看，如果整复杂了，就失去初衷了

Semi 的色阶算法没有开源，我们也感到很遗憾~
